"""add trade corridor models

Revision ID: 1ebef639f513
Revises: 24b770ed7694
Create Date: 2026-03-04 00:21:04.336782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebef639f513'
down_revision: Union[str, Sequence[str], None] = '24b770ed7694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_corridors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('from_country_code', sa.String(length=2), nullable=False),
    sa.Column('to_country_code', sa.String(length=2), nullable=False),
    sa.Column('corridor_type', sa.String(length=20), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('transit_countries', sa.String(length=50), nullable=True),
    sa.Column('key_border_posts', sa.String(length=200), nullable=True),
    sa.Column('key_ports', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_corridors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_corridors_corridor_code'), ['corridor_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_trade_corridors_from_country_code'), ['from_country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_corridors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_corridors_to_country_code'), ['to_country_code'], unique=False)

    op.create_table('corridor_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('transport_score', sa.Float(), nullable=True),
    sa.Column('fx_score', sa.Float(), nullable=True),
    sa.Column('trade_volume_score', sa.Float(), nullable=True),
    sa.Column('logistics_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('payment_score', sa.Float(), nullable=True),
    sa.Column('corridor_composite', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=15), nullable=True),
    sa.Column('bottleneck', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data_sources_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['trade_corridors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corridor_id', 'assessment_date', name='uq_corridor_assessment_date')
    )
    with op.batch_alter_table('corridor_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corridor_assessments_assessment_date'), ['assessment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_corridor_assessments_corridor_id'), ['corridor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corridor_assessments_id'), ['id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_is_revoked'), ['is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_is_revoked'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('corridor_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corridor_assessments_id'))
        batch_op.drop_index(batch_op.f('ix_corridor_assessments_corridor_id'))
        batch_op.drop_index(batch_op.f('ix_corridor_assessments_assessment_date'))

    op.drop_table('corridor_assessments')
    with op.batch_alter_table('trade_corridors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_corridors_to_country_code'))
        batch_op.drop_index(batch_op.f('ix_trade_corridors_id'))
        batch_op.drop_index(batch_op.f('ix_trade_corridors_from_country_code'))
        batch_op.drop_index(batch_op.f('ix_trade_corridors_corridor_code'))

    op.drop_table('trade_corridors')
    # ### end Alembic commands ###
