"""add ussd_consents table and upgrade financial columns to Numeric

Revision ID: 9c0a738cbe8a
Revises: e4ae3694d20f
Create Date: 2026-03-04 21:25:45.936162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0a738cbe8a'
down_revision: Union[str, Sequence[str], None] = 'e4ae3694d20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ussd_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('service_code', sa.String(length=20), nullable=True),
    sa.Column('consent_lang', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ussd_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ussd_consents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ussd_consents_phone_hash'), ['phone_hash'], unique=True)

    with op.batch_alter_table('bank_dossier_scores', schema=None) as batch_op:
        batch_op.alter_column('loan_amount_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('max_recommended_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('bilateral_trade', schema=None) as batch_op:
        batch_op.alter_column('export_value_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('import_value_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_trade_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('trade_balance_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('business_data_submissions', schema=None) as batch_op:
        batch_op.alter_column('tax_credit_earned_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('cbdc_cross_border_payments', schema=None) as batch_op:
        batch_op.alter_column('amount_source',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('amount_target',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('fx_rate_applied',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('platform_fee_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('rail_fee_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_cost_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('cbdc_eligible_collateral', schema=None) as batch_op:
        batch_op.alter_column('face_value_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('market_value_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('collateral_value_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_fx_positions', schema=None) as batch_op:
        batch_op.alter_column('net_position_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('position_limit_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_bought_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_sold_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('cbdc_fx_rates', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('inverse_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_ledger_entries', schema=None) as batch_op:
        batch_op.alter_column('amount_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('balance_after_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_monetary_aggregates', schema=None) as batch_op:
        batch_op.alter_column('total_ecfa_circulation',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('retail_balance_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('merchant_balance_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('bank_balance_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('agent_balance_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_minted_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_burned_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_p2p_volume_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_merchant_volume_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_cross_border_volume_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('m0_base_money_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('m1_narrow_money_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('m2_broad_money_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_required_reserves_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_held_reserves_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_lending_facility_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_deposit_facility_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_interest_paid_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_demurrage_collected_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_reserve_penalties_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('cbdc_monetary_policy_decisions', schema=None) as batch_op:
        batch_op.alter_column('ecfa_circulation_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('cbdc_offline_vouchers', schema=None) as batch_op:
        batch_op.alter_column('amount_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_rate_locks', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('inverse_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('locked_amount_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_reserve_requirements', schema=None) as batch_op:
        batch_op.alter_column('deposit_base_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('required_amount_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('current_holding_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('surplus_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('deficiency_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('accrued_penalty_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('accrued_remuneration_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('cbdc_settlements', schema=None) as batch_op:
        batch_op.alter_column('gross_amount_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('net_amount_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_standing_facilities', schema=None) as batch_op:
        batch_op.alter_column('amount_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('interest_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('collateral_value_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('cbdc_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('fee_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appeal_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('appeal_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('appeal_submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('auto_unfreeze_date', sa.Date(), nullable=True))
        batch_op.alter_column('balance_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('available_balance_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('hold_amount_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('daily_limit_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('balance_limit_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('daily_spent_ecfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('commodity_prices', schema=None) as batch_op:
        batch_op.alter_column('price_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('contract_milestones', schema=None) as batch_op:
        batch_op.alter_column('value_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('country_indices', schema=None) as batch_op:
        batch_op.alter_column('trade_value_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('daily_activity_declarations', schema=None) as batch_op:
        batch_op.alter_column('price_local',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('payment_amount_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('data_tokens', schema=None) as batch_op:
        batch_op.alter_column('token_value_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('token_value_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('divergence_snapshots', schema=None) as batch_op:
        batch_op.alter_column('volume_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('faso_meabo_workers', schema=None) as batch_op:
        batch_op.alter_column('daily_rate_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('total_earned_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('forecast_results', schema=None) as batch_op:
        batch_op.alter_column('forecast_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('lower_1sigma',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('upper_1sigma',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('lower_2sigma',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('upper_2sigma',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('macro_indicators', schema=None) as batch_op:
        batch_op.alter_column('gdp_usd_billions',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('payment_disbursements', schema=None) as batch_op:
        batch_op.alter_column('amount_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('amount_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.alter_column('credits_used',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('stock_market_data', schema=None) as batch_op:
        batch_op.alter_column('market_cap_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('volume_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('market_cap_local',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('fx_rate_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('tax_credit_ledger', schema=None) as batch_op:
        batch_op.alter_column('amount_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('cumulative_earned_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('cumulative_used_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('tax_liability_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('cap_absolute_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('tokenization_daily_aggregates', schema=None) as batch_op:
        batch_op.alter_column('citizen_total_paid_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('business_tax_credits_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('x402_balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('ussd_commodity_reports', schema=None) as batch_op:
        batch_op.alter_column('price_local',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('price_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('ussd_daily_aggregates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_condition_score', sa.Float(), nullable=True))

    with op.batch_alter_table('ussd_mobile_money_flows', schema=None) as batch_op:
        batch_op.alter_column('total_value_local',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('total_value_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('avg_transaction_local',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('avg_transaction_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('fx_rate_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('ussd_trade_declarations', schema=None) as batch_op:
        batch_op.alter_column('declared_value_local',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('declared_value_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('wasi_composites', schema=None) as batch_op:
        batch_op.alter_column('composite_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('wasi_procurement_records', schema=None) as batch_op:
        batch_op.alter_column('total_value_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('avg_contract_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('worker_check_ins', schema=None) as batch_op:
        batch_op.alter_column('daily_rate_cfa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('x402_tiers', schema=None) as batch_op:
        batch_op.alter_column('query_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('x402_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('balance_before',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('balance_after',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x402_transactions', schema=None) as batch_op:
        batch_op.alter_column('balance_after',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('balance_before',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('x402_tiers', schema=None) as batch_op:
        batch_op.alter_column('query_cost',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('worker_check_ins', schema=None) as batch_op:
        batch_op.alter_column('daily_rate_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('wasi_procurement_records', schema=None) as batch_op:
        batch_op.alter_column('avg_contract_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_value_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('wasi_composites', schema=None) as batch_op:
        batch_op.alter_column('composite_value',
               existing_type=sa.Numeric(precision=18, scale=4, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('ussd_trade_declarations', schema=None) as batch_op:
        batch_op.alter_column('declared_value_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('declared_value_local',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('ussd_mobile_money_flows', schema=None) as batch_op:
        batch_op.alter_column('fx_rate_usd',
               existing_type=sa.Numeric(precision=12, scale=6, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('avg_transaction_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('avg_transaction_local',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_value_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_value_local',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('ussd_daily_aggregates', schema=None) as batch_op:
        batch_op.drop_column('route_condition_score')

    with op.batch_alter_table('ussd_commodity_reports', schema=None) as batch_op:
        batch_op.alter_column('price_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price_local',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('x402_balance',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('tokenization_daily_aggregates', schema=None) as batch_op:
        batch_op.alter_column('business_tax_credits_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('citizen_total_paid_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('tax_credit_ledger', schema=None) as batch_op:
        batch_op.alter_column('cap_absolute_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('tax_liability_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('cumulative_used_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('cumulative_earned_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('stock_market_data', schema=None) as batch_op:
        batch_op.alter_column('fx_rate_usd',
               existing_type=sa.Numeric(precision=12, scale=6, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('market_cap_local',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('volume_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('market_cap_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.alter_column('credits_used',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('payment_disbursements', schema=None) as batch_op:
        batch_op.alter_column('amount_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('macro_indicators', schema=None) as batch_op:
        batch_op.alter_column('gdp_usd_billions',
               existing_type=sa.Numeric(precision=18, scale=4, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('forecast_results', schema=None) as batch_op:
        batch_op.alter_column('upper_2sigma',
               existing_type=sa.Numeric(precision=18, scale=4, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('lower_2sigma',
               existing_type=sa.Numeric(precision=18, scale=4, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('upper_1sigma',
               existing_type=sa.Numeric(precision=18, scale=4, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('lower_1sigma',
               existing_type=sa.Numeric(precision=18, scale=4, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('forecast_value',
               existing_type=sa.Numeric(precision=18, scale=4, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('faso_meabo_workers', schema=None) as batch_op:
        batch_op.alter_column('total_earned_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('daily_rate_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('divergence_snapshots', schema=None) as batch_op:
        batch_op.alter_column('volume_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('data_tokens', schema=None) as batch_op:
        batch_op.alter_column('token_value_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('token_value_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('daily_activity_declarations', schema=None) as batch_op:
        batch_op.alter_column('payment_amount_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price_local',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('country_indices', schema=None) as batch_op:
        batch_op.alter_column('trade_value_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('contract_milestones', schema=None) as batch_op:
        batch_op.alter_column('value_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('commodity_prices', schema=None) as batch_op:
        batch_op.alter_column('price_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_wallets', schema=None) as batch_op:
        batch_op.alter_column('daily_spent_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('balance_limit_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('daily_limit_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('hold_amount_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('available_balance_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('balance_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('auto_unfreeze_date')
        batch_op.drop_column('appeal_submitted_at')
        batch_op.drop_column('appeal_reason')
        batch_op.drop_column('appeal_status')

    with op.batch_alter_table('cbdc_transactions', schema=None) as batch_op:
        batch_op.alter_column('total_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('fee_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_standing_facilities', schema=None) as batch_op:
        batch_op.alter_column('collateral_value_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('interest_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_settlements', schema=None) as batch_op:
        batch_op.alter_column('net_amount_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('gross_amount_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_reserve_requirements', schema=None) as batch_op:
        batch_op.alter_column('accrued_remuneration_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('accrued_penalty_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('deficiency_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('surplus_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('current_holding_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('required_amount_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('deposit_base_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_rate_locks', schema=None) as batch_op:
        batch_op.alter_column('locked_amount_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('inverse_rate',
               existing_type=sa.Numeric(precision=12, scale=6, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=12, scale=6, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_offline_vouchers', schema=None) as batch_op:
        batch_op.alter_column('amount_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_monetary_policy_decisions', schema=None) as batch_op:
        batch_op.alter_column('ecfa_circulation_total',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('cbdc_monetary_aggregates', schema=None) as batch_op:
        batch_op.alter_column('total_reserve_penalties_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_demurrage_collected_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_interest_paid_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_deposit_facility_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_lending_facility_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_held_reserves_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_required_reserves_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('m2_broad_money_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('m1_narrow_money_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('m0_base_money_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_cross_border_volume_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_merchant_volume_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_p2p_volume_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_burned_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_minted_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('agent_balance_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('bank_balance_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('merchant_balance_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('retail_balance_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_ecfa_circulation',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_ledger_entries', schema=None) as batch_op:
        batch_op.alter_column('balance_after_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('amount_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_fx_rates', schema=None) as batch_op:
        batch_op.alter_column('inverse_rate',
               existing_type=sa.Numeric(precision=12, scale=6, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=12, scale=6, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_fx_positions', schema=None) as batch_op:
        batch_op.alter_column('total_sold_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_bought_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('position_limit_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('net_position_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('cbdc_eligible_collateral', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'cbdc_wallets', ['owner_wallet_id'], ['wallet_id'])
        batch_op.alter_column('collateral_value_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('market_value_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('face_value_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cbdc_cross_border_payments', schema=None) as batch_op:
        batch_op.alter_column('total_cost_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('rail_fee_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('platform_fee_ecfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('fx_rate_applied',
               existing_type=sa.Numeric(precision=12, scale=6, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount_target',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount_source',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('business_data_submissions', schema=None) as batch_op:
        batch_op.alter_column('tax_credit_earned_cfa',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('bilateral_trade', schema=None) as batch_op:
        batch_op.alter_column('trade_balance_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_trade_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('import_value_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('export_value_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('bank_dossier_scores', schema=None) as batch_op:
        batch_op.alter_column('max_recommended_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('loan_amount_usd',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('ussd_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ussd_consents_phone_hash'))
        batch_op.drop_index(batch_op.f('ix_ussd_consents_id'))

    op.drop_table('ussd_consents')
    # ### end Alembic commands ###
