"""add alert and webhook models

Revision ID: e4ae3694d20f
Revises: 1ebef639f513
Create Date: 2026-03-04 06:58:31.128287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ae3694d20f'
down_revision: Union[str, Sequence[str], None] = '1ebef639f513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_source', sa.String(length=30), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('commodity_code', sa.String(length=20), nullable=True),
    sa.Column('event_type_filter', sa.String(length=30), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('webhook_secret', sa.String(length=128), nullable=False),
    sa.Column('credit_cost_per_delivery', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_event_source'), ['event_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_user_id'), ['user_id'], unique=False)

    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_source', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('credits_charged', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_deliveries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_deliveries_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_deliveries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_deliveries_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_alert_deliveries_rule_id'))
        batch_op.drop_index(batch_op.f('ix_alert_deliveries_id'))

    op.drop_table('alert_deliveries')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_is_active'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_id'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_event_source'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_country_code'))

    op.drop_table('alert_rules')
    # ### end Alembic commands ###
